title: Look at these ferretsss
author: some ferret
email: carrasco.ex01.com
description: > # this means to ignore newlines until "baseurl:"
  Look at these ferrets named Trish and Ruka. A blog for their lives and stuff they do.
  I hope you can enjoy hem as much as I do everyday.

# social links
twitter_username: yoshicave # DO NOT include the @ character, or else the build will fail!
github_username:  yoshiEXE # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
